### ISSUE TITLE
Export fails

### ISSUE THREAD

**Issue by Snudl** [Falano/kritaSpritesheetManager#4]
Does the script currently work on your end?

I tried it with Krita 4.2.5 and a build from master after someone in the Krita Discord mentioned they had trouble with it too. The dialog grays out after clicking OK unless I uncheck Remove individual frames and there's usually only 1 PNG frame ending with a random (?) high number in the export folder, or an empty frame in the parent folder when that option is unchecked.

By the way, if I try to run the script on a new document that hasn't been saved yet, it outputs this error:
```
IndexError
Python 3.7.4: /usr/bin/python3
Thu Aug 15 03:36:14 2019

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/snu/.local/share/krita/pykrita/spritesheetExporter/uispritesheetexporter.py in showExportDialog(self=<spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>)
  324     def showExportDialog(self):
  325         self.doc = self.app.activeDocument()
  326         self.resetExportDir()
  327         self.mainDialog.setWindowTitle(i18n("SpritesheetExporter"))
  328         self.mainDialog.setSizeGripEnabled(True)
self = <spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>
self.resetExportDir = <bound method UISpritesheetExporter.resetExportD...pritesheetexporter.UISpritesheetExporter object>>

 /home/snu/.local/share/krita/pykrita/spritesheetExporter/uispritesheetexporter.py in resetExportDir(self=<spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>)
  344     def resetExportDir(self):
  345         if self.doc:
  346             self.exportPath = Path(self.doc.fileName()).parents[0]
  347             self.exportDirTx.setText(str(self.exportPath))
  348 
self = <spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>
self.exportPath = PosixPath('/home/snu/Concepts')
global Path = <class 'pathlib.Path'>
self.doc = <PyKrita.krita.Document object>
self.doc.fileName = <built-in method fileName of Document object>
).parents undefined

 /usr/lib/python3.7/pathlib.py in __getitem__(self=<PosixPath.parents>, idx=0)
  601     def __getitem__(self, idx):
  602         if idx < 0 or idx >= len(self):
  603             raise IndexError(idx)
  604         return self._pathcls._from_parsed_parts(self._drv, self._root,
  605                                                 self._parts[:-idx - 1])
builtinIndexError = <class 'IndexError'>
idx = 0
IndexError: 0
    __cause__ = None
    __class__ = <class 'IndexError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of IndexError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of IndexError object>
    __doc__ = 'Sequence index out of range.'
    __eq__ = <method-wrapper '__eq__' of IndexError object>
    __format__ = <built-in method __format__ of IndexError object>
    __ge__ = <method-wrapper '__ge__' of IndexError object>
    __getattribute__ = <method-wrapper '__getattribute__' of IndexError object>
    __gt__ = <method-wrapper '__gt__' of IndexError object>
    __hash__ = <method-wrapper '__hash__' of IndexError object>
    __init__ = <method-wrapper '__init__' of IndexError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of IndexError object>
    __lt__ = <method-wrapper '__lt__' of IndexError object>
    __ne__ = <method-wrapper '__ne__' of IndexError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of IndexError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of IndexError object>
    __repr__ = <method-wrapper '__repr__' of IndexError object>
    __setattr__ = <method-wrapper '__setattr__' of IndexError object>
    __setstate__ = <built-in method __setstate__ of IndexError object>
    __sizeof__ = <built-in method __sizeof__ of IndexError object>
    __str__ = <method-wrapper '__str__' of IndexError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = (0,)
    with_traceback = <built-in method with_traceback of IndexError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/snu/.local/share/krita/pykrita/spritesheetExporter/uispritesheetexporter.py", line 326, in showExportDialog
    self.resetExportDir()
  File "/home/snu/.local/share/krita/pykrita/spritesheetExporter/uispritesheetexporter.py", line 346, in resetExportDir
    self.exportPath = Path(self.doc.fileName()).parents[0]
  File "/usr/lib/python3.7/pathlib.py", line 603, in __getitem__
    raise IndexError(idx)
IndexError: 0
```

**Comment by Falano** [comment]
The manual says "Don't switch active window while the script is exporting, or it will get interrupted and, most likely, not create the final spritesheet and leave rogue sprite exports (and maybe a sprite export folder, depending on your settings) in your export folder. If this happens, just close the plugin window, remove the unneeded files and try exporting again.". Maybe you just had too big or too long an animation to export, and you didn't wait long enough for it to finish? I usually see spritesheets for pixel art, and those are pretty light, but if you try to create really big spritesheets it will be slower.

I just downloaded 4.2.5, and it worked; on twelve 64x64 frames it worked great, on twelve 1280x1280 it was slower, and greyed out while the script was working, but I just waited ten seconds or so and it worked. I had kept the default options, so Remove individual frames was checked.
I did a few tests where I tried checking my file explorer and moving around the temporary folder while the script was working, and it didn't like it (staying greyed out and sometimes not removing the last frame), so just stay on krita while it works.

If you still have issues, try sending me a screenshot of your export options, as well as your animation parameters (image size, number of frames, number of layers), so I can try to produce the bug on my end?

The reason it doesn't work for an unsaved document is likely because the default directory for the spritesheet is the .kra's directory, which, if it hasn't been saved, it kinda doesn't have. I hadn't thought about this possibility; if it's easy I'll fix it in a couple days. - edit: fixed it just now

(sorry, I don't check the discord; thank for bringing this to my attention)

**Comment by Snudl** [comment]
Aha, I managed to fix it.
The script needs to wait for processing to finish, that's why it fails on big and complex documents - or at least that's how it appears to me. I added a `doc.waitForDone()` statement each at the beginning of the 2 while loops where the image operations happen. Maybe you have a better solution. Do you want a pull request?

Also thanks for fixing the unsaved document error already and also answering on Discord :)

**Comment by Falano** [comment]
Great, thanks! Yes, please do a pull request. If it works better than it does now, then I don't have a better solution.

You're welcome :) I'm kinda invested in people being able to use this.

**Comment by Falano** [comment]
sorry for the delay; I merged it. Thanks!
